INSERT INTO Client_Type(name,description) VALUES('Standard','Standard client type');
INSERT INTO Client_Type(name,description) VALUES('Premium','Premium client type');
INSERT INTO Client_Type(name,description) VALUES('VIP','VIP client type');
INSERT INTO Client_Type(name,description) VALUES('Corporate','Corporate client type');
INSERT INTO Client_Type(name,description) VALUES('Student','Student client type');
INSERT INTO Account_Type(name,description) VALUES('Checking','Standard checking account');
INSERT INTO Account_Type(name,description) VALUES('Savings','Standard savings account');
INSERT INTO Account_Type(name,description) VALUES('Business','Business account');
INSERT INTO Account_Type(name,description) VALUES('Retirement','Retirement account');
INSERT INTO Account_Type(name,description) VALUES('Investment','Investment account');
INSERT INTO Transaction_Type(name,description) VALUES('Deposit','Money added');
INSERT INTO Transaction_Type(name,description) VALUES('Withdrawal','Money removed');
INSERT INTO Transaction_Type(name,description) VALUES('Transfer','Transfer between accounts');
INSERT INTO Transaction_Type(name,description) VALUES('Purchase','Debit card purchase');
INSERT INTO Transaction_Type(name,description) VALUES('Fee','Service fee');
INSERT INTO Financial_Product_Type(name,description) VALUES('Stock','Equity product');
INSERT INTO Financial_Product_Type(name,description) VALUES('Bond','Debt product');
INSERT INTO Financial_Product_Type(name,description) VALUES('Mutual Fund','Managed portfolio product');
INSERT INTO Financial_Product_Type(name,description) VALUES('ETF','Exchange traded fund');
INSERT INTO Financial_Product_Type(name,description) VALUES('Certificate of Deposit','Timed deposit product');
INSERT INTO Risk_Profile(risk_level,return_rate,description) VALUES('Low',2.5,'Low risk, stable returns');
INSERT INTO Risk_Profile(risk_level,return_rate,description) VALUES('Moderate',5.0,'Moderate risk level');
INSERT INTO Risk_Profile(risk_level,return_rate,description) VALUES('High',8.5,'High risk/reward');
INSERT INTO Risk_Profile(risk_level,return_rate,description) VALUES('Aggressive',12.0,'Very high volatility');
INSERT INTO Risk_Profile(risk_level,return_rate,description) VALUES('Conservative',3.0,'Capital preservation');